---
- mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
  when: create_db

- mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: '{{ mysql_db_name }}.*:ALL'
    append_privs: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
  when: create_db

- name: filling in env file
  lineinfile:
    dest: "{{ dest_path }}/www/env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  loop:
    - { regexp: '^mysql_db_name', line: 'mysql_db_name = {{ mysql_db_name }}' }
    - { regexp: '^mysql_user', line: 'mysql_user = {{ mysql_user }}' }
    - { regexp: '^mysql_pass', line: 'mysql_pass = {{ mysql_pass }}' }
  when: create_db
