---
ansible_python_interpreter: "/usr/bin/python3"
thostip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
NODEJS_VERSION: 16
mysql_root_password: "jaJj8Xueh0NZzT75"
http_host: "test.org"
http_conf: "test.org.conf"
http_port: "80"

