---
- hosts: "{{ hostname|default('test') }}"
  vars_files:
    - vars/default.yml
  roles:
    - { role: common, become: true }
    - { role: redis, become: true }
    - { role: certbot, become: true }
    - { role: ufw, become: true }
    - { role: node, become: false }
    - { role: postgresql, become: true }
    - { role: nginx, become: true }

