---
- mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
  when: create_db

- mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: '{{ mysql_db_name }}.*:ALL'
    append_privs: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
  when: create_db